# Generated by Django 4.2.7 on 2023-11-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badhabits',
            options={'verbose_name': 'Вредная привычка', 'verbose_name_plural': 'Вредные привычки'},
        ),
    ]
