# Generated by Django 4.2.7 on 2023-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0004_alter_badhabits_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bad_habits',
            field=models.ManyToManyField(default=None, to='quit.badhabits', verbose_name='Плохие привычки'),
        ),
    ]
