# Generated by Django 4.2.7 on 2023-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0005_alter_user_bad_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bad_habits',
            field=models.ManyToManyField(default=None, null=True, to='quit.badhabits', verbose_name='Плохие привычки'),
        ),
    ]
