# Generated by Django 4.2.7 on 2023-11-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0006_alter_user_bad_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bad_habits',
            field=models.ManyToManyField(blank=True, to='quit.badhabits', verbose_name='Плохие привычки'),
        ),
    ]
