# Generated by Django 4.2.7 on 2023-12-08 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0010_remove_chat_users_user_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='second_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Собеседник'),
        ),
    ]
