# Generated by Django 4.2.7 on 2023-12-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0012_remove_chat_messages_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='quit.chat', verbose_name='Чат'),
        ),
    ]
