# Generated by Django 4.2.7 on 2023-12-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0015_remove_user_chats_user_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, to='quit.chat', verbose_name='Чаты'),
        ),
    ]
